# 菜单配置（若不需要某项可直接删除）
menu:
  # 首页
  - id: home
    link: /
    icon: home
    class: menu-home
  # 归档
  - id: archives
    link: /archives
    icon: archive
    class: menu-archive
  # 分类
  - id: category
    link: javascript:;
    category: true
    icon: th
    class: menu-category
  # 读书
 # - id: reading
 #   link: /reading
 #   icon: book
 #   class: menu-reading
  # 关于
 # - id: about
 #   link: /about
 #   icon: user
 #   class: menu-about
  # 搜索
  - id: search
    link: "#search"
    icon: search
    class: menu-search modal-trigger
  - id: board
    link: /board
    icon: edit
    class: menu-about 
  # 后台评论管理
  - id: admin
    link: "http://renjiabao.duoshuo.com/admin/"
    icon: user
    class: menu-search modal-trigger
# 颜色配置
color:
  header: grey darken-2
  footer: grey darken-2
  page_nav: grey darken-1
  side_nav: grey darken-1
  tag: grey
  article_title_link: grey
  link: blue  #高亮
  pagination: grey darken-2
  tab: grey
  archive_item: grey
  #fab: grey
  fab_2: grey darken-2
  #fab_3: yellow darken-1
  new: grey
  about_header: grey
  about_title: grey

excerpt_link: More
archive_yearly: false

widgets: #配置页脚显示哪些小挂件
  - tagcloud
  - recent_posts
  - duoshuo_recent_comments

# 版权信息
copyright: © 2010-2016 wolego (QQ:552333981)

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname: renjiabao

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics: 58073081
# 高亮的主题，若为空则使用默认主题
google_code_prettify: prettify-tomorrow-night-eighties

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: false